@startuml get_device_list
script --> __init__
script --> get_device_list
get_device_list --> _kids_timer
_kids_timer --> _home
_home --> login
login --> _driver_setup
hnote over _driver_setup: create instance
_driver_setup --> login
hnote over login: set username\nset password\nput login button
login --> _home
hnote over _home: put home icon
_home --> _kids_timer
hnote over _kids_timer: put kids timer panel
_kids_timer --> get_device_list
loop 0..2
loop 0..127
hnote over get_device_list: find_element devi_j\nput dev panel\nget dev name\nget dev MAC
end
end
hnote over get_device_list: save dev list
get_device_list --> script
@enduml

@startuml page_transition
[*] --> login_page
login_page --> home
login_page --> dupplicate_login
dupplicate_login --> home
home --> kids_timer_page
home --> advanced_settings
kids_timer_page --> device_X_detail
device_X_detail --> kids_timer_page
advanced_settings --> mac_limit_config
mac_limit_config --> mac_limit_config_edit
mac_limit_config_edit --> mac_limit_config
kids_timer_page --> home
device_X_detail --> home
advanced_settings --> home
mac_limit_config --> home
mac_limit_config_edit --> home
home --> login_page
dupplicate_login --> login_page
kids_timer_page --> login_page
device_X_detail --> login_page
advanced_settings --> login_page
mac_limit_config --> login_page
mac_limit_config_edit --> login_page
@enduml

@startuml del_proc
autonumber 1.1
script --> config.toml: load_config()
script <-- config.toml: username,password
autonumber 2.1
script --> airstation: login(username,password)
script <-- airstation: config_page
script --> airstation: transit_page()
script <-- airstation: mac_list
loop mac_list
hnote over script: matching mac address
end
autonumber 3.1
script --> airstation: delete
airstation --> script: response
script --> airstation: logout()
@enduml

@startuml del_func
start
:load_config();
if (login()) is (True) then
:page_transit();
:get_mac_list();
if (mac in maclist) is (True) then
:delete_mac(hostname);
endif;
:logout();
endif;
end
@enduml

@startuml add_func
start
:load_config();
if (login()) is (True) then
:page_transit();
:get_mac_list();
if (mac in maclist) is (True) then
else
:add_mac(hostname);
endif;
:logout();
endif;
end
@enduml

@startuml usecase
left to right direction
title ユースケース図
actor USER as u
rectangle system {
    actor TIMER as t
    usecase "delete_mac()" as del_func
    usecase "add_mac()" as add_func
}
u --> del_func: "@bot del hostname"
u --> add_func: "@bot add hostname"
del_func <-- t
add_func <-- t
@enduml